..normalization in test data

In [1]:
import numpy as np
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X= iris.data
y = iris.target

In [4]:
X[:5,:]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

##  StandarScaler in scikit-learn

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
standarScaler = StandardScaler()

In [9]:
standarScaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [11]:
standarScaler.mean_

array([ 5.80916667,  3.0575    ,  3.7275    ,  1.1825    ])

In [12]:
standarScaler.scale_

array([ 0.82036535,  0.44453393,  1.7439401 ,  0.75029578])

In [13]:
standarScaler.transform(X_train)

array([[-1.47393679,  1.22037928, -1.5639872 , -1.30948358],
       [-0.13307079,  3.02001693, -1.27728011, -1.04292204],
       [ 1.08589829,  0.09560575,  0.38562104,  0.28988568],
       [-1.23014297,  0.77046987, -1.21993869, -1.30948358],
       [-1.7177306 ,  0.32056046, -1.39196294, -1.30948358],
       [ 0.59831066, -1.25412249,  0.72966956,  0.95628954],
       [ 0.72020757,  0.32056046,  0.44296246,  0.42316645],
       [-0.74255534,  0.99542457, -1.27728011, -1.30948358],
       [-0.98634915,  1.22037928, -1.33462153, -1.30948358],
       [-0.74255534,  2.34515281, -1.27728011, -1.44276436],
       [-0.01117388, -0.80421307,  0.78701097,  0.95628954],
       [ 0.23261993,  0.77046987,  0.44296246,  0.55644722],
       [ 1.08589829,  0.09560575,  0.5576453 ,  0.42316645],
       [-0.49876152,  1.8952434 , -1.39196294, -1.04292204],
       [-0.49876152,  1.44533399, -1.27728011, -1.30948358],
       [-0.37686461, -1.47907719, -0.01576889, -0.24323741],
       [ 0.59831066, -0.

In [14]:
X_train = standarScaler.transform(X_train)

In [15]:
X_test = standarScaler.transform(X_test)

## using KNN to classify for data standardization

In [16]:
from sklearn.neighbors import KNeighborsClassifier

In [17]:
knn_clf = KNeighborsClassifier(n_neighbors= 3)

In [18]:
knn_clf.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [19]:
knn_clf.score(X_test,y_test)

1.0

. X_test must be standardization

In [20]:
knn_clf.score(X_test,y_test)

1.0

## using our own standardScaler

In [22]:
from preprocessing import StandarScalar
my_standarScalar = StandarScaler()
my_standardScalar.fit(X_train)

ImportError: cannot import name 'StandarScalar'